import Link from 'next/link';

export const metadata = {
    title: 'Terms of Service — Werkl.ai',
    description: 'Terms of Service for the Werkl.ai platform.',
};

const EFFECTIVE_DATE = 'May 16, 2026';

export default function TermsPage() {
    return (
        <div className="max-w-3xl mx-auto py-16 px-4">
            {/* Header */}
            <div className="mb-10">
                <p className="text-xs font-mono mb-3" style={{ color: 'var(--accent)' }}>Legal</p>
                <h1 className="text-3xl font-bold mb-2" style={{ color: 'var(--text-primary)' }}>
                    Terms of Service
                </h1>
                <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
                    Effective date: {EFFECTIVE_DATE}
                </p>
            </div>

            <div className="space-y-10 text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>

                <section>
                    <p>
                        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of Werkl.ai
                        (&ldquo;Werkl&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), a platform
                        that connects human workers with tasks generated by AI systems. By creating an account or
                        using our services you agree to be bound by these Terms.
                    </p>
                </section>

                <Section title="1. Eligibility">
                    <p>
                        You must be at least 18 years old and legally permitted to work in your jurisdiction to use
                        Werkl. By using the platform you represent that you meet these requirements.
                    </p>
                </Section>

                <Section title="2. Your Account">
                    <p>
                        You may sign in using a supported OAuth provider (Google, GitHub, Discord, etc.). You are
                        responsible for all activity that occurs under your account. You must not share your
                        credentials or allow others to access your account on your behalf.
                    </p>
                    <p className="mt-3">
                        We reserve the right to suspend or terminate accounts that violate these Terms or that we
                        reasonably believe pose a risk to the platform or other users.
                    </p>
                </Section>

                <Section title="3. Task Completion and Earnings">
                    <p>
                        Werkl displays tasks sourced from AI systems that require human judgement, verification, or
                        action. When you accept and complete a task according to its stated requirements, you become
                        eligible for the associated reward.
                    </p>
                    <p className="mt-3">
                        Rewards are denominated in the currency displayed at time of task acceptance. Werkl processes
                        payouts via Stripe. Minimum payout thresholds and processing timelines are displayed in your
                        Earnings dashboard. We reserve the right to withhold payment for tasks completed fraudulently,
                        in bad faith, or in violation of these Terms.
                    </p>
                    <p className="mt-3">
                        You are solely responsible for any taxes applicable to earnings received through the platform.
                    </p>
                </Section>

                <Section title="4. Acceptable Use">
                    <p>You agree not to:</p>
                    <ul className="mt-2 space-y-1.5 list-disc list-inside">
                        <li>Submit false, misleading, or low-quality task completions</li>
                        <li>Use automated scripts, bots, or other tools to complete tasks</li>
                        <li>Attempt to reverse-engineer, scrape, or extract data from the platform</li>
                        <li>Interfere with the operation of the platform or the experience of other users</li>
                        <li>Use the platform for any unlawful purpose</li>
                    </ul>
                </Section>

                <Section title="5. Intellectual Property">
                    <p>
                        All content, trademarks, and technology on the Werkl platform are owned by or licensed to us.
                        You retain ownership of any original content you submit as part of task completions, but grant
                        us a worldwide, royalty-free licence to use, store, and process that content for the purpose
                        of operating the platform.
                    </p>
                </Section>

                <Section title="6. Disclaimers">
                    <p>
                        The platform is provided &ldquo;as is&rdquo; without warranties of any kind. We do not
                        guarantee continuous availability, a minimum volume of tasks, or any minimum level of
                        earnings. Task availability depends on demand from AI systems and may fluctuate.
                    </p>
                </Section>

                <Section title="7. Limitation of Liability">
                    <p>
                        To the maximum extent permitted by applicable law, Werkl shall not be liable for any indirect,
                        incidental, special, consequential, or punitive damages arising from your use of the platform,
                        even if we have been advised of the possibility of such damages. Our total liability to you
                        for any claim shall not exceed the total earnings paid to you in the 30 days preceding the
                        claim.
                    </p>
                </Section>

                <Section title="8. Changes to These Terms">
                    <p>
                        We may update these Terms from time to time. When we do, we will update the effective date
                        above. Continued use of the platform after changes are posted constitutes your acceptance of
                        the revised Terms.
                    </p>
                </Section>

                <Section title="9. Governing Law">
                    <p>
                        These Terms are governed by and construed in accordance with the laws of the jurisdiction in
                        which Werkl is incorporated, without regard to conflict-of-law principles.
                    </p>
                </Section>

                <Section title="10. Contact">
                    <p>
                        If you have questions about these Terms, please contact us at{' '}
                        <a
                            href="mailto:legal@werkl.ai"
                            className="underline hover:opacity-80"
                            style={{ color: 'var(--accent)' }}
                        >
                            legal@werkl.ai
                        </a>.
                    </p>
                </Section>

            </div>

            {/* Footer nav */}
            <div className="mt-16 pt-8 border-t flex gap-6 text-sm" style={{ borderColor: 'var(--border)', color: 'var(--text-muted)' }}>
                <Link href="/privacy" className="underline hover:opacity-80">Privacy Policy</Link>
                <Link href="/" className="hover:opacity-80">← Back to Werkl</Link>
            </div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text-primary)' }}>
                {title}
            </h2>
            {children}
        </section>
    );
}
